language: php

php:
  - 7.2
  - nightly

matrix:
  allow_failures:
    - php: nightly
  fast_finish: true

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer self-update
  - composer update --no-interaction --no-progress --no-suggest --prefer-dist

script:
  - composer phpunit
  - composer phpcs
  - composer infection