language: php

php:
  - 7.2
  - nightly

matrix:
  allow_failures:
    - php: nightly
  fast_finish: true

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - if command -v phpenv 2>/dev/null; then phpenv config-rm xdebug.ini; else echo "Not Found 'phpenv'"; fi
  - composer self-update
  - composer update --no-interaction --no-progress --no-suggest --prefer-dist
  - mkdir -p build

script:
  - composer phpcs
  - composer phpmd_build
  - if [ `command -v phpdbg` ]; then composer phpunit_build; fi
  - if [ -d "./build/phpunit/" ]; then composer infection_build; fi
