language: php

php:
  - '7.2'
  - '7.3'
  - nightly

matrix:
  allow_failures:
    - php: nightly
  fast_finish: true

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer self-update
  - composer update --no-interaction --no-progress --no-suggest --prefer-dist
  - mkdir -p build

script:
  - composer phpcs
  - composer phpmd_build
  - if [ `command -v phpdbg` ]; then composer phpunit_build; fi
  - if [ -d "./build/phpunit/" ]; then composer infection_build; fi
