language: php

php:
  - 7.2
  - nightly

matrix:
  allow_failures:
    - php: nightly
  fast_finish: true

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer update --no-interaction --no-progress --no-suggest --prefer-dist
  - mkdir -p build

script:
  - composer phpcs
  - composer phpmd_build
  - composer phpunit_build
  - composer infection_build
