language: php

php:
  - 7.2
  - nightly

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer self-update
  - composer update --no-interaction --no-progress --no-suggest --prefer-dist

script:
  - composer phpunit
  - composer phpcs