#!/bin/bash

EXIT=0

composer phpcs
CODE=$?
if [[ ${CODE} ]]; then
  EXIT=1
fi

composer phpmd
CODE=$?
if [[ ${CODE} ]]; then
  EXIT=1
fi

composer phpunit
CODE=$?
if [[ ${CODE} ]]; then
  EXIT=1
fi

composer infection
CODE=$?
if [[ ${CODE} ]]; then
  EXIT=1
fi

exit ${EXIT}